#!/usr/bin/env bash

set -xe

# Update sources
apt-get update -y

# Install dependancies
apt-get install -y \
    git \
    wget \
    bzip2 \
    zip \
    unzip \
    sqlite3 \
    libcurl4-gnutls-dev \
    libsqlite3-0 \
    libsqlite3-dev \
    libxml2 \
    libxml2-dev \
    libxslt1.1 \
    libxslt1-dev \
    libzip2 \
    libzip-dev \
    zlib1g-dev \

# Remove cached lists
rm -rf /var/lib/apt/lists/*

# Install extensions
docker-php-ext-install \
    curl \
    mbstring \
    xml \
    json \
    zip \
    # pdo \
    # pdo_sqlite \
    # dom \
    # simplexml \
&& docker-php-source delete

# Remove compile dependancies, to save space
apt-get purge -y \
    libcurl4-gnutls-dev \
    libsqlite3-0 libsqlite3-dev \
    libxml2-dev \
    libxslt1-dev \
    libzip-dev \
    zlib1g-dev

# Do some autoremoving, if required
apt-get autoremove -y --purge

# Clean up
apt-get -y clean

# Install composer
EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
wget -O composer-setup.php https://getcomposer.org/installer
ACTUAL_SIGNATURE=$(openssl sha384 -r composer-setup.php | awk '{print $1}')

if [ "$EXPECTED_SIGNATURE" = "$ACTUAL_SIGNATURE" ]
then
    php composer-setup.php --quiet --install-dir=/usr/local/bin --filename=composer
    rm composer-setup.php
else
    >&2 echo "ERROR: Invalid Composer signature"
    rm composer-setup.php
    exit 1
fi

composer install --global phpunit
