#!/bin/sh
set -e

echo "WARNING"
echo "This script is running as non-elevated user"

echo "# server-information"

# Export some version information
php --version

echo " "
composer --version | grep --invert-match 'Do not run Composer as root/super user'

echo " "
phpunit --version

echo "# user commands"

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

# Run main command
exec "$@"
